version: 2

sources:
  - name: raw
    database: raw  # Explicitly specify ClickHouse database
    tables:
      - name: chinook_grp3___albums
      - name: chinook_grp3___artists
      - name: chinook_grp3___customers
      - name: chinook_grp3___employees
      - name: chinook_grp3___genres
      - name: chinook_grp3___invoice_lines
      - name: chinook_grp3___invoices
      - name: chinook_grp3___tracks